baseurl = "http://gliheng.github.io/Blackhole/"
languageCode = "en-us"
title = "Blackhole"
description = "An elite web proxy debugger for desktop and mobile."

[params]
	description = "An elite web proxy debugger for desktop and mobile."
